apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: highb
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jx3-jenkins-quickstart
    scheduler: in-repo
  jenkinsServers:
  - groups:
    - owner: highb
      provider: https://github.com
      providerKind: github
      repositories:
      - name: jx3-app
    server: jenkins-in-a-box
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
